// Photo
export const REQUEST_FEED_PHOTOS = 'REQUEST_FEED_PHOTOS'
export const RECEIVE_FEED_PHOTOS = 'RECEIVE_FEED_PHOTOS'
export const REQUEST_PHOTO_SIZE = 'REQUEST_PHOTO_SIZE'
export const RECEIVE_PHOTO_SIZE = 'RECEIVE_PHOTO_SIZE'

// UI Filter
export const SORT_BY_TYPE = 'SORT_BY_TYPE'
export const PICK_PHOTO_SIZE = 'PICK_PHOTO_SIZE'
export const CHANGE_VIEW_TYPE = 'CHANGE_VIEW_TYPE'