// Photo
export const REQUEST_FEED_PHOTOS = 'REQUEST_FEED_PHOTOS'
export const RECEIVE_FEED_PHOTOS = 'RECEIVE_FEED_PHOTOS'
export const REQUEST_PHOTO_SIZE = 'REQUEST_PHOTO_SIZE'
export const RECEIVE_PHOTO_SIZE = 'RECEIVE_PHOTO_SIZE'

// Filters
export const SORT_BY_TYPE = 'SORT_BY_TYPE'